services:
  registry:
    image: daanilo/registry:dev
    build:
      context: .
      args:
        SERVICE: registry
    environment:
      INSTANCE_ID: registry-1
      BACKEND: ap
      CLUSTER_MEMBERS: registry:7000
    ports:
      - "7000:7000"   # gRPC server
      - "10000:10000" # observability server

  load-balancer:
    image: daanilo/load-balancer:dev
    build:
      context: .
      args:
        SERVICE: load-balancer
    environment:
      REGISTRY_ADDRESSES: registry:7000
    ports:
      - "8000:8000"   # HTTP server
      - "10010:10010" # observability server
    depends_on:
      - registry

  mock-service:
    image: daanilo/mock-service:dev
    build:
      context: .
      args:
        SERVICE: mock-service
    environment:
      NAME: example-service
      INSTANCE_ID: mock-service-1
      REGISTRY_ADDRESSES: registry:7000
    ports:
      - "9000:9000"   # HTTP server
      - "10020:10020" # observability server
    depends_on:
      - registry

  dozzle:
    image: amir20/dozzle:latest
    profiles: ["debug"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:8081:8080"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8082:3000"
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "8083:9090"
    depends_on:
      - registry
      - load-balancer
      - mock-service
