{
 "title": "TPIII Overview",
 "tags": [ "tpiii" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}